#define WINDOW_TITLE "This is a title"
#define LOW_RES_SCREEN_WIDTH 480
#define LOW_RES_SCREEN_HEIGHT 270
#define DEFAULT_WINDOW_WIDTH (LOW_RES_SCREEN_WIDTH * 3)
#define DEFAULT_WINDOW_HEIGHT (LOW_RES_SCREEN_HEIGHT * 3)
#define AUDIO_SAMPLE_RATE 44100
