#define WINDOW_TITLE "This is a title"
#define PROGRAM_FILENAME "app"
#define DEFAULT_WINDOW_WIDTH 1344
#define DEFAULT_WINDOW_HEIGHT 756
#define LOW_RES_SCREEN_WIDTH 480
#define LOW_RES_SCREEN_HEIGHT 270
