#define WINDOW_TITLE "This is a title"
#define PROGRAM_FILENAME "app"
#define DEFAULT_WINDOW_WIDTH 960
#define DEFAULT_WINDOW_HEIGHT 540
#define LOW_RES_SCREEN_WIDTH 480
#define LOW_RES_SCREEN_HEIGHT 270
#define AUDIO_SAMPLE_RATE 44100
