name: build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  Windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Build binary
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        .\build_win.bat
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install SDL2
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev
    - name: Build binary
      run: ./build_linux.sh
