name: Test

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  Windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        .\test_win.bat

  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: ./test_linux.sh
